INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('AF','AFG','004','93','Afghanistan');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('AL','ALB','008','355','Albania');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('DZ','DZA','012','213','Algeria');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('AS','ASM','016','1-684','American Samoa');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('AD','AND','020','376','Andorra');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('AO','AGO','024','244','Angola');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('AI','AIA','660','1-264','Anguilla');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('AQ','ATA','010','672','Antarctica');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('AG','ATG','028','1-268','Antigua and Barbuda');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('AR','ARG','032','54','Argentina');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('AM','ARM','051','374','Armenia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('AW','ABW','533','297','Aruba');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('AU','AUS','036','61','Australia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('AT','AUT','040','43','Austria');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('AZ','AZE','031','994','Azerbaijan');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('BS','BHS','044','1-242','Bahamas (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('BH','BHR','048','973','Bahrain');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('BD','BGD','050','880','Bangladesh');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('BB','BRB','052','1-246','Barbados');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('BY','BLR','112','375','Belarus');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('BE','BEL','056','32','Belgium');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('BZ','BLZ','084','501','Belize');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('BJ','BEN','204','229','Benin');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('BM','BMU','060','1-441','Bermuda');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('BT','BTN','064','975','Bhutan');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('BO','BOL','068','591','Bolivia (Plurinational State of)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('BQ','BES','535','599','Bonaire, Sint Eustatius and Saba');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('BA','BIH','070','387','Bosnia and Herzegovina');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('BW','BWA','072','267','Botswana');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('BV','BVT','074','47','Bouvet Island');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('BR','BRA','076','55','Brazil');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('IO','IOT','086','246','British Indian Ocean Territory (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('BN','BRN','096','673','Brunei Darussalam');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('BG','BGR','100','359','Bulgaria');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('BF','BFA','854','226','Burkina Faso');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('BI','BDI','108','257','Burundi');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('CV','CPV','132','238','Cabo Verde');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('KH','KHM','116','855','Cambodia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('CM','CMR','120','237','Cameroon');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('CA','CAN','124','1','Canada');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('KY','CYM','136','1-345','Cayman Islands (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('CF','CAF','140','236','Central African Republic (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('TD','TCD','148','235','Chad');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('CL','CHL','152','56','Chile');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('CN','CHN','156','86','China');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('CX','CXR','162','61','Christmas Island');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('CC','CCK','166','61','Cocos (Keeling) Islands (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('CO','COL','170','57','Colombia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('KM','COM','174','269','Comoros (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('CD','COD','180','243','Congo (the Democratic Republic of the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('CG','COG','178','242','Congo (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('CK','COK','184','682','Cook Islands (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('CR','CRI','188','506','Costa Rica');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('HR','HRV','191','385','Croatia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('CU','CUB','192','53','Cuba');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('CW','CUW','531','599','Curaçao');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('CY','CYP','196','357','Cyprus');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('CZ','CZE','203','420','Czechia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('CI','CIV','384','225','Côte d''Ivoire');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('DK','DNK','208','45','Denmark');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('DJ','DJI','262','253','Djibouti');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('DM','DMA','212','1-767','Dominica');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('DO','DOM','214','1-809,1-829,1-849','Dominican Republic (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('EC','ECU','218','593','Ecuador');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('EG','EGY','818','20','Egypt');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('SV','SLV','222','503','El Salvador');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('GQ','GNQ','226','240','Equatorial Guinea');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('ER','ERI','232','291','Eritrea');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('EE','EST','233','372','Estonia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('SZ','SWZ','748','268','Eswatini');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('ET','ETH','231','251','Ethiopia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('FK','FLK','238','500','Falkland Islands (the) [Malvinas]');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('FO','FRO','234','298','Faroe Islands (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('FJ','FJI','242','679','Fiji');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('FI','FIN','246','358','Finland');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('FR','FRA','250','33','France');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('GF','GUF','254','594','French Guiana');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('PF','PYF','258','689','French Polynesia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('TF','ATF','260','262','French Southern Territories (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('GA','GAB','266','241','Gabon');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('GM','GMB','270','220','Gambia (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('GE','GEO','268','995','Georgia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('DE','DEU','276','49','Germany');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('GH','GHA','288','233','Ghana');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('GI','GIB','292','350','Gibraltar');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('GR','GRC','300','30','Greece');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('GL','GRL','304','299','Greenland');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('GD','GRD','308','1-473','Grenada');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('GP','GLP','312','590','Guadeloupe');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('GU','GUM','316','1-671','Guam');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('GT','GTM','320','502','Guatemala');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('GG','GGY','831','44-1481','Guernsey');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('GN','GIN','324','224','Guinea');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('GW','GNB','624','245','Guinea-Bissau');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('GY','GUY','328','592','Guyana');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('HT','HTI','332','509','Haiti');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('HM','HMD','334','672','Heard Island and McDonald Islands');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('VA','VAT','336','379','Vatican City');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('HN','HND','340','504','Honduras');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('HK','HKG','344','852','Hong Kong');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('HU','HUN','348','36','Hungary');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('IS','ISL','352','354','Iceland');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('IN','IND','356','91','India');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('ID','IDN','360','62','Indonesia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('IR','IRN','364','98','Iran (Islamic Republic of)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('IQ','IRQ','368','964','Iraq');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('IE','IRL','372','353','Ireland');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('IM','IMN','833','44-1624','Isle of Man');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('IL','ISR','376','972','Israel');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('IT','ITA','380','39','Italy');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('JM','JAM','388','1-876','Jamaica');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('JP','JPN','392','81','Japan');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('JE','JEY','832','44-1534','Jersey');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('JO','JOR','400','962','Jordan');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('KZ','KAZ','398','7','Kazakhstan');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('KE','KEN','404','254','Kenya');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('KI','KIR','296','686','Kiribati');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('KP','PRK','408','850','Korea (the Democratic People''s Republic of)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('KR','KOR','410','82','Korea (the Republic of)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('KW','KWT','414','965','Kuwait');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('KG','KGZ','417','996','Kyrgyzstan');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('LA','LAO','418','856','Lao People''s Democratic Republic (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('LV','LVA','428','371','Latvia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('LB','LBN','422','961','Lebanon');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('LS','LSO','426','266','Lesotho');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('LR','LBR','430','231','Liberia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('LY','LBY','434','218','Libya');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('LI','LIE','438','423','Liechtenstein');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('LT','LTU','440','370','Lithuania');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('LU','LUX','442','352','Luxembourg');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('MO','MAC','446','853','Macao');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('MG','MDG','450','261','Madagascar');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('MW','MWI','454','265','Malawi');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('MY','MYS','458','60','Malaysia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('MV','MDV','462','960','Maldives');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('ML','MLI','466','223','Mali');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('MT','MLT','470','356','Malta');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('MH','MHL','584','692','Marshall Islands (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('MQ','MTQ','474','596','Martinique');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('MR','MRT','478','222','Mauritania');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('MU','MUS','480','230','Mauritius');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('YT','MYT','175','262','Mayotte');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('MX','MEX','484','52','Mexico');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('FM','FSM','583','691','Micronesia (Federated States of)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('MD','MDA','498','373','Moldova (the Republic of)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('MC','MCO','492','377','Monaco');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('MN','MNG','496','976','Mongolia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('ME','MNE','499','382','Montenegro');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('MS','MSR','500','1-664','Montserrat');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('MA','MAR','504','212','Morocco');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('MZ','MOZ','508','258','Mozambique');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('MM','MMR','104','95','Myanmar');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('NA','NAM','516','264','Namibia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('NR','NRU','520','674','Nauru');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('NP','NPL','524','977','Nepal');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('NL','NLD','528','31','Netherlands (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('NC','NCL','540','687','New Caledonia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('NZ','NZL','554','64','New Zealand');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('NI','NIC','558','505','Nicaragua');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('NE','NER','562','227','Niger (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('NG','NGA','566','234','Nigeria');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('NU','NIU','570','683','Niue');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('NF','NFK','574','672','Norfolk Island');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('MP','MNP','580','1-670','Northern Mariana Islands (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('NO','NOR','578','47','Norway');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('OM','OMN','512','968','Oman');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('PK','PAK','586','92','Pakistan');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('PW','PLW','585','680','Palau');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('PS','PSE','275','970','Palestine, State of');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('PA','PAN','591','507','Panama');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('PG','PNG','598','675','Papua New Guinea');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('PY','PRY','600','595','Paraguay');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('PE','PER','604','51','Peru');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('PH','PHL','608','63','Philippines (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('PN','PCN','612','64','Pitcairn');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('PL','POL','616','48','Poland');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('PT','PRT','620','351','Portugal');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('PR','PRI','630','1-787,1-939','Puerto Rico');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('QA','QAT','634','974','Qatar');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('MK','MKD','807','389','Republic of North Macedonia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('RO','ROU','642','40','Romania');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('RU','RUS','643','7','Russian Federation (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('RW','RWA','646','250','Rwanda');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('RE','REU','638','262','Réunion');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('BL','BLM','652','590','Saint Barthélemy');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('SH','SHN','654','290','Saint Helena, Ascension and Tristan da Cunha');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('KN','KNA','659','1-869','Saint Kitts and Nevis');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('LC','LCA','662','1-758','Saint Lucia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('MF','MAF','663','590','Saint Martin (French part)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('PM','SPM','666','508','Saint Pierre and Miquelon');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('VC','VCT','670','1-784','Saint Vincent and the Grenadines');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('WS','WSM','882','685','Samoa');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('SM','SMR','674','378','San Marino');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('ST','STP','678','239','Sao Tome and Principe');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('SA','SAU','682','966','Saudi Arabia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('SN','SEN','686','221','Senegal');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('RS','SRB','688','381','Serbia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('SC','SYC','690','248','Seychelles');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('SL','SLE','694','232','Sierra Leone');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('SG','SGP','702','65','Singapore');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('SX','SXM','534','1-721','Sint Maarten (Dutch part)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('SK','SVK','703','421','Slovakia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('SI','SVN','705','386','Slovenia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('SB','SLB','090','677','Solomon Islands');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('SO','SOM','706','252','Somalia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('ZA','ZAF','710','27','South Africa');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('GS','SGS','239','500','South Georgia and the South Sandwich Islands');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('SS','SSD','728','211','South Sudan');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('ES','ESP','724','34','Spain');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('LK','LKA','144','94','Sri Lanka');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('SD','SDN','729','249','Sudan (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('SR','SUR','740','597','Suriname');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('SJ','SJM','744','47','Svalbard and Jan Mayen');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('SE','SWE','752','46','Sweden');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('CH','CHE','756','41','Switzerland');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('SY','SYR','760','963','Syrian Arab Republic');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('TW','TWN','158','886','Taiwan (Province of China)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('TJ','TJK','762','992','Tajikistan');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('TZ','TZA','834','255','Tanzania, United Republic of');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('TH','THA','764','66','Thailand');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('TL','TLS','626','670','Timor-Leste');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('TG','TGO','768','228','Togo');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('TK','TKL','772','690','Tokelau');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('TO','TON','776','676','Tonga');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('TT','TTO','780','1-868','Trinidad and Tobago');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('TN','TUN','788','216','Tunisia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('TR','TUR','792','90','Turkey');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('TM','TKM','795','993','Turkmenistan');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('TC','TCA','796','1-649','Turks and Caicos Islands (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('TV','TUV','798','688','Tuvalu');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('UG','UGA','800','256','Uganda');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('UA','UKR','804','380','Ukraine');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('AE','ARE','784','971','United Arab Emirates (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('GB','GBR','826','44','United Kingdom of Great Britain and Northern Ireland (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('UM','UMI','581',null,'United States Minor Outlying Islands (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('US','USA','840','1','United States of America (the)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('UY','URY','858','598','Uruguay');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('UZ','UZB','860','998','Uzbekistan');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('VU','VUT','548','678','Vanuatu');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('VE','VEN','862','58','Venezuela (Bolivarian Republic of)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('VN','VNM','704','84','Viet Nam');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('VG','VGB','092','1-284','Virgin Islands (British)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('VI','VIR','850','1-340','Virgin Islands (U.S.)');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('WF','WLF','876','681','Wallis and Futuna');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('EH','ESH','732','212','Western Sahara');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('YE','YEM','887','967','Yemen');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('ZM','ZMB','894','260','Zambia');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('ZW','ZWE','716','263','Zimbabwe');
INSERT INTO country (isoCode, isoCodeA3, isoNumCode, countryCode, nameEn) VALUES ('AX','ALA','248','358','Åland Islands');